version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5500:5500"
    volumes:
      - ./backend:/usr/src/backend
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
    environment:
      - NODE_ENV=development
